# Generated by Django 4.2.16 on 2024-11-24 03:13

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="national_code",
            field=models.CharField(
                default=1273064755,
                max_length=10,
                validators=[accounts.validators.validate_iranian_national_code],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_english_persian",
                        message="Only English(A-Z) and Persian(ی-ا) characters are allowed.",
                        regex="^[A-Za-z\\u0600-\\u06FF]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_english_persian",
                        message="Only English(A-Z) and Persian(ی-ا) characters are allowed.",
                        regex="^[A-Za-z\\u0600-\\u06FF]+$",
                    )
                ],
            ),
        ),
    ]
